version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: browna2/titan-ox
    restart: unless-stopped
    ports:
      - "3000:8080"
    volumes:
      - .:/home/node/app/